In [37]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [38]:
df=pd.read_csv(r"C:\Users\kirti\Desktop\AI Engineer\End-To-End Project\Movie Recommendation System\data\ratings.csv")

In [39]:
movies_meta=pd.read_csv(r"C:\Users\kirti\Desktop\AI Engineer\End-To-End Project\Movie Recommendation System\data\movies_metadata.csv")

C:\Users\kirti\AppData\Local\Temp\ipykernel_21940\1612413770.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  movies_meta=pd.read_csv(r"C:\Users\kirti\Desktop\AI Engineer\End-To-End Project\Movie Recommendation System\data\movies_metadata.csv")

In [40]:
df.head()

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [41]:
movies_meta=movies_meta.rename(columns={"id":"movieId"})
movies_meta.head()

,adult,belongs_to_collection,budget,genres,homepage,movieId,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [42]:
movies_meta["movieId"]=pd.to_numeric(movies_meta["movieId"],errors="coerce") ## we use to_numeric() when we have to handle errors in data, .astype() throws error (only use when clean)

In [43]:
print(df.shape[0],movies_meta.shape[0])

26024289 45466

In [52]:
merg_df=pd.merge(df,movies_meta, on="movieId",how="inner") ## as i'll only need table that has both movie id and its name

In [53]:
merg_df.columns

Index(['userId', 'movieId', 'rating', 'timestamp', 'adult',
       'belongs_to_collection', 'budget', 'genres', 'homepage', 'imdb_id',
       'original_language', 'original_title', 'overview', 'popularity',
       'poster_path', 'production_companies', 'production_countries',
       'release_date', 'revenue', 'runtime', 'spoken_languages', 'status',
       'tagline', 'title', 'video', 'vote_average', 'vote_count'],
      dtype='object')

In [55]:
fdf=merg_df[['userId', 'movieId', 'rating', 'timestamp', 'title']]
fdf

,userId,movieId,rating,timestamp,title
0,1,110,1.0,1425941529,Three Colors: Red
1,1,147,4.5,1425942435,The 400 Blows
2,1,858,5.0,1425941523,Sleepless in Seattle
3,1,1246,5.0,1425941556,Rocky Balboa
4,1,1968,4.0,1425942148,Fools Rush In
...,...,...,...,...,...
11437632,270896,48780,5.0,1257031830,Boat
11437633,270896,49530,4.0,1257034436,In Time
11437634,270896,54001,4.0,1257034331,The Traveler
11437635,270896,54503,4.0,1257033886,The Mystery of Chess Boxing
11437636,270896,58559,5.0,1257031564,Confession of a Child of the Century

In [58]:
## fdf.pivot_table(index="userId",columns="movieId",values="rating")        Pivot table didn't worked because too many movies and 90 % + are sparse.

In [60]:
from scipy.sparse import csr_matrix
sparse_matrix=csr_matrix((fdf["rating"],(fdf["userId"],fdf["movieId"])))
## Sparse matrix only stores non-zero values to save space and be memmory efficient.

Stored in this format:

(user1, movie2) = 4  
(user1, movie8) = 5  
(user2, movie1) = 3

In [62]:
print(sparse_matrix.shape)

(270897, 176274)

In [9]:
df.shape

(26024289, 4)

In [10]:
df.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)