In [67]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [68]:
df=pd.read_csv(r"C:\Users\kirti\Desktop\AI Engineer\End-To-End Project\Movie Recommendation System\data\ratings.csv")

In [69]:
movies_meta=pd.read_csv(r"C:\Users\kirti\Desktop\AI Engineer\End-To-End Project\Movie Recommendation System\data\movies_metadata.csv")

C:\Users\kirti\AppData\Local\Temp\ipykernel_5116\1612413770.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  movies_meta=pd.read_csv(r"C:\Users\kirti\Desktop\AI Engineer\End-To-End Project\Movie Recommendation System\data\movies_metadata.csv")

In [70]:
df.head()

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [71]:
movies_meta=movies_meta.rename(columns={"id":"movieId"})
movies_meta.head()

,adult,belongs_to_collection,budget,genres,homepage,movieId,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [72]:
movies_meta["movieId"]=pd.to_numeric(movies_meta["movieId"],errors="coerce") ## we use to_numeric() when we have to handle errors in data, .astype() throws error (only use when clean)

In [73]:
print(df.shape[0],movies_meta.shape[0])

26024289 45466

In [74]:
merg_df=pd.merge(df,movies_meta, on="movieId",how="inner") ## as i'll only need table that has both movie id and its name

In [75]:
merg_df.columns

Index(['userId', 'movieId', 'rating', 'timestamp', 'adult',
       'belongs_to_collection', 'budget', 'genres', 'homepage', 'imdb_id',
       'original_language', 'original_title', 'overview', 'popularity',
       'poster_path', 'production_companies', 'production_countries',
       'release_date', 'revenue', 'runtime', 'spoken_languages', 'status',
       'tagline', 'title', 'video', 'vote_average', 'vote_count'],
      dtype='object')

In [76]:
fdf=merg_df[['userId', 'movieId', 'rating', 'timestamp', 'title']]
fdf

,userId,movieId,rating,timestamp,title
0,1,110,1.0,1425941529,Three Colors: Red
1,1,147,4.5,1425942435,The 400 Blows
2,1,858,5.0,1425941523,Sleepless in Seattle
3,1,1246,5.0,1425941556,Rocky Balboa
4,1,1968,4.0,1425942148,Fools Rush In
...,...,...,...,...,...
11437632,270896,48780,5.0,1257031830,Boat
11437633,270896,49530,4.0,1257034436,In Time
11437634,270896,54001,4.0,1257034331,The Traveler
11437635,270896,54503,4.0,1257033886,The Mystery of Chess Boxing
11437636,270896,58559,5.0,1257031564,Confession of a Child of the Century

In [77]:
## fdf.pivot_table(index="userId",columns="movieId",values="rating")        Pivot table didn't worked because too many movies and 90 % + are sparse.

In [78]:
from scipy.sparse import csr_matrix ## Compressed sparse rows
csr_matrix=csr_matrix((fdf["rating"],(fdf["userId"],fdf["movieId"])))
## Sparse matrix only stores non-zero values to save space and be memmory efficient.

Stored in this format:

- data = [3,2,1,4]
- indices = [4,2,3,6]
- indptr = [0,1,3,4]

Row 0 : 

data[0:1] = 3 rating

indices[0:1] = 4 th column

Row 1 : 

data[1:3] = 2,1 rating

indices[1:3] = 2nd, 3rd column

In [79]:
rows,cols=csr_matrix.nonzero()
print(rows,"\n", cols)

[     1      1      1 ... 270896 270896 270896]
 [  110   147   858 ... 54001 54503 58559]

In [81]:
rows.shape

(11436568,)

In [82]:
cols.shape

(11436568,)

In [83]:
test_size=round(0.2*csr_matrix.shape[0])
test_size

54179

In [87]:
test_rows=rows[test_idx]    ## Test-set indexes
test_cols=cols[test_idx]

In [88]:
train_matrix=csr_matrix.copy()

In [89]:
train_matrix[test_rows,test_cols]=0
train_matrix.eliminate_zeros() ## removes zeros from storage

In [138]:
train_matrix.shape

(270897, 176274)

In [145]:
np.array(train_matrix.sum(axis=1)).flatten()/ train_matrix.getnnz(axis=1)

C:\Users\kirti\AppData\Local\Temp\ipykernel_5116\3405331463.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(train_matrix.sum(axis=1)).flatten()/ train_matrix.getnnz(axis=1)

array([       nan, 4.1       , 3.        , ..., 2.56034483, 4.23529412,
       3.96564885], shape=(270897,))

- SVD does decompostion of matrix into smaller matrix of latent feature which has least reconstruction error.
- Original matrix = latent matrix (user) x latent matrix (movie)
- Truncated SVD uses only top_n latent features to reconstruct matrix for better generalization and faster prediction.

In [90]:
from sklearn.decomposition import TruncatedSVD ## Creates two matrix from single matrix having same latent features.
model=TruncatedSVD(n_components=50)
user_latent=model.fit_transform(train_matrix)  ## User latent features

Matrix Factorization idea shows up in:
- PCA
- SVD
- Word embeddings (Tf-idf Vectorizer)
- Transformers (attention factorization idea)

In [91]:
movie_latent=model.components_.T   ## Movie latent features (Transpose because reconstruction made movie latent transpose)

In [92]:
print("User latent:",user_latent.shape,"Movie_latent",movie_latent.shape)

User latent: (270897, 50) Movie_latent (176274, 50)

Why cosine be better sometimes rather than dot product?

In [104]:
user_latent[test_rows[0]] @ movie_latent[test_cols[0]]

np.float64(1.146207858921269)

In [114]:
y_pred=[]
for i,j in zip(test_rows,test_cols):
    pred=user_latent[i] @ movie_latent[j]
    y_pred.append(pred)

In [115]:
y_test=[]
for i,j in zip(test_rows,test_cols):
    pred=csr_matrix[i,j]
    y_test.append(pred)

In [123]:
y_test

[np.float64(4.0),
 np.float64(1.0),
 np.float64(3.0),
 np.float64(2.5),
 np.float64(2.0),
 np.float64(4.5),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(3.5),
 np.float64(0.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(1.5),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(2.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(0.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(1.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(2.5),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(4.5),
 np.float64(4.5),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.5),
 np.float64(3.5),
 np.float64(2.0),
 np.float64(2.0),
 np.float64(2.5),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(1.5),
 np.float64(5.0),
 np.float64(4.5),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(2.5),
 np.float64(2.5),
 np.float64(1.0),
 np.float64(4.5),
 np.float64(2.5),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.5),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.5),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.5),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(2.5),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(2.5),
 np.float64(3.0),
 np.float64(2.5),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(2.5),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(2.5),
 np.float64(2.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(4.5),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(1.5),
 np.float64(2.5),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(2.5),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(2.5),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(2.5),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(1.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(0.5),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(2.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(4.5),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(1.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(2.5),
 np.float64(5.0),
 np.float64(2.5),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(4.5),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(4.5),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(4.5),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(2.5),
 np.float64(2.5),
 np.float64(1.0),
 np.float64(4.5),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(2.5),
 np.float64(4.0),
 np.float64(2.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(2.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(2.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(2.0),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(2.5),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(2.0),
 np.float64(2.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(0.5),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(2.5),
 np.float64(5.0),
 np.float64(2.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(4.5),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.5),
 np.float64(3.5),
 np.float64(4.5),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(2.5),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(1.5),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(4.5),
 np.float64(2.0),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(2.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(2.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(2.5),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(2.5),
 np.float64(2.0),
 np.float64(1.0),
 np.float64(3.0),
 np.float64(0.5),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(2.0),
 np.float64(4.0),
 np.float64(1.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(1.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(2.5),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(2.5),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(1.0),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(4.5),
 np.float64(5.0),
 np.float64(2.5),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(2.5),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(3.5),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(0.5),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(1.0),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(0.5),
 np.float64(2.5),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(1.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(2.0),
 np.float64(5.0),
 np.float64(1.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(1.0),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(4.5),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(1.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(1.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(2.5),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(2.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(2.0),
 np.float64(1.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(2.5),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(2.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(4.5),
 np.float64(0.5),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(1.5),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(2.5),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(0.5),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(1.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(4.5),
 np.float64(2.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(2.5),
 np.float64(3.5),
 np.float64(2.5),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(1.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(4.5),
 np.float64(1.5),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(2.5),
 np.float64(3.5),
 np.float64(2.5),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(2.5),
 np.float64(0.5),
 np.float64(4.0),
 np.float64(4.5),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(1.0),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(3.5),
 np.float64(0.5),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(2.0),
 np.float64(2.0),
 np.float64(5.0),
 np.float64(2.0),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(2.5),
 np.float64(3.5),
 np.float64(3.5),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(1.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(2.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(2.5),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(2.5),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(1.5),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(1.0),
 np.float64(2.5),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.5),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(2.0),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(2.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(2.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(0.5),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(5.0),
 np.float64(4.5),
 np.float64(2.0),
 np.float64(5.0),
 np.float64(2.5),
 np.float64(2.5),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(1.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(2.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(2.5),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(2.5),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(1.0),
 np.float64(4.0),
 np.float64(4.5),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(3.5),
 np.float64(2.5),
 np.float64(2.5),
 np.float64(4.5),
 np.float64(4.5),
 np.float64(3.0),
 np.float64(1.0),
 np.float64(2.5),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(2.0),
 np.float64(2.0),
 np.float64(1.0),
 np.float64(4.5),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(4.5),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(4.5),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(2.0),
 np.float64(4.0),
 np.float64(2.0),
 np.float64(2.0),
 np.float64(5.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(4.5),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(2.5),
 np.float64(4.0),
 np.float64(2.0),
 np.float64(3.5),
 np.float64(2.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(1.0),
 np.float64(3.0),
 np.float64(2.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(1.0),
 np.float64(0.5),
 np.float64(0.5),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(4.5),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(5.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(4.0),
 np.float64(3.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(1.0),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(3.5),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(2.5),
 np.float64(3.0),
 ...]

In [122]:
y_pred

[np.float64(1.146207858921269),
 np.float64(0.34440280304310367),
 np.float64(0.7843384498554314),
 np.float64(0.497588944774029),
 np.float64(1.037298190937788),
 np.float64(1.3304161224799416),
 np.float64(0.09168105193659626),
 np.float64(0.9393488817222649),
 np.float64(3.041384354829224),
 np.float64(1.945162684170373),
 np.float64(2.4733371550088847),
 np.float64(0.2987128870797286),
 np.float64(1.1420133123596545),
 np.float64(0.3727283800125857),
 np.float64(1.3023935195671639),
 np.float64(2.0340739373593637),
 np.float64(1.1243860644719803),
 np.float64(-0.03819899926513571),
 np.float64(0.8989516814141172),
 np.float64(0.03811957906851045),
 np.float64(0.9466064909384847),
 np.float64(1.0627289618460414),
 np.float64(2.3991448984674717),
 np.float64(1.0814824559639604),
 np.float64(1.7293312931985463),
 np.float64(3.389555405359352),
 np.float64(0.3386300244100485),
 np.float64(2.1907729791088357),
 np.float64(3.0265914105413088),
 np.float64(0.006093319714296978),
 np.float64(0.5520087709743228),
 np.float64(-0.05251134118266917),
 np.float64(1.905547313377801),
 np.float64(0.6121953249773445),
 np.float64(0.12462646056997531),
 np.float64(2.460953095301272),
 np.float64(1.0141533488113708),
 np.float64(0.10775654845263835),
 np.float64(-0.03977472009602233),
 np.float64(0.05042165359995221),
 np.float64(1.4308808775824255),
 np.float64(2.919823017244425),
 np.float64(0.09016715116297419),
 np.float64(3.3289043285754394),
 np.float64(1.5918798883499563),
 np.float64(2.98053506670877),
 np.float64(0.6632846110343119),
 np.float64(1.5430523337983817),
 np.float64(1.1501247111811177),
 np.float64(0.004223402089942607),
 np.float64(0.3563879151207369),
 np.float64(0.39943690365321194),
 np.float64(1.7241505454187798),
 np.float64(1.1059993785428512),
 np.float64(1.817046471864119),
 np.float64(-0.041543264525159745),
 np.float64(0.8378660008419946),
 np.float64(0.7840074100741432),
 np.float64(0.5528632555356139),
 np.float64(2.39213582014807),
 np.float64(0.5023116621962921),
 np.float64(0.6634544214466338),
 np.float64(3.0029572557157116),
 np.float64(0.06623791484850679),
 np.float64(0.003279829548761354),
 np.float64(0.06739629597928133),
 np.float64(0.11692289615435003),
 np.float64(1.2779201367401545),
 np.float64(0.4899984410201968),
 np.float64(1.70956957119268),
 np.float64(1.972398320292362),
 np.float64(0.19490509013299695),
 np.float64(1.1456542168033037),
 np.float64(0.5259231693173946),
 np.float64(0.17204814007983626),
 np.float64(0.4184940769406774),
 np.float64(0.6470367864088427),
 np.float64(2.9167410324861027),
 np.float64(0.4858917072052019),
 np.float64(1.4037227950698647),
 np.float64(2.0955051602643007),
 np.float64(0.11076010772457134),
 np.float64(0.0918949630362768),
 np.float64(0.7634676264604101),
 np.float64(1.7878667127405241),
 np.float64(2.3161337017811814),
 np.float64(0.2236626098706011),
 np.float64(3.329455981654353),
 np.float64(0.42940669799976433),
 np.float64(0.9139432058581004),
 np.float64(1.4044393632282541),
 np.float64(0.5607795165539496),
 np.float64(0.33611535738154424),
 np.float64(0.2930219568083664),
 np.float64(0.9625692685821423),
 np.float64(0.1557564102816112),
 np.float64(1.6682196431814948),
 np.float64(1.0256385030940873),
 np.float64(1.5972272665338103),
 np.float64(0.4246300530841096),
 np.float64(1.1212954044959245),
 np.float64(0.039828802743215375),
 np.float64(1.5007798950427644),
 np.float64(1.5849703464444973),
 np.float64(0.12729771420252242),
 np.float64(1.5610665834219228),
 np.float64(1.979758371308762),
 np.float64(0.6603916729762533),
 np.float64(0.3072372992557406),
 np.float64(0.015302939690193834),
 np.float64(0.1736488041351527),
 np.float64(0.44735428750681555),
 np.float64(0.8681059401816429),
 np.float64(0.8058479319146159),
 np.float64(3.1487593292191747),
 np.float64(0.2610171999183278),
 np.float64(0.18936230714806093),
 np.float64(1.0010930937457159),
 np.float64(0.562299900891528),
 np.float64(0.10578267959230825),
 np.float64(0.6626928266226271),
 np.float64(0.6975763008558366),
 np.float64(1.0576105547403265),
 np.float64(2.630680632960159),
 np.float64(0.04611468273166257),
 np.float64(1.7199210445579787),
 np.float64(2.164388179749312),
 np.float64(2.252780891482053),
 np.float64(0.8633426167408653),
 np.float64(0.03533628677233025),
 np.float64(0.009810441149647558),
 np.float64(0.762365699471779),
 np.float64(2.2231369394840126),
 np.float64(0.09464581149208677),
 np.float64(1.1130868682018296),
 np.float64(0.37039906568637393),
 np.float64(0.3990970832636186),
 np.float64(2.553836699261984),
 np.float64(0.7622087485900179),
 np.float64(0.07393503186650786),
 np.float64(0.18881311662635433),
 np.float64(0.1514052049637965),
 np.float64(2.8420517649176684),
 np.float64(0.056264777480520646),
 np.float64(1.4587029117932995),
 np.float64(-0.04550168302816635),
 np.float64(1.0238589823782949),
 np.float64(1.6050125040935193),
 np.float64(2.9738832366913828),
 np.float64(0.0379759046171156),
 np.float64(3.10748033411138),
 np.float64(0.4988213532291504),
 np.float64(0.025054740402008856),
 np.float64(1.5907534023054428),
 np.float64(2.0524255819743646),
 np.float64(0.1715144720186856),
 np.float64(0.6639305245884928),
 np.float64(0.7543464327284684),
 np.float64(1.424000134688165),
 np.float64(0.36162447460835273),
 np.float64(1.4308808775824255),
 np.float64(0.4057819597199031),
 np.float64(0.11081623174742762),
 np.float64(1.2467328907058077),
 np.float64(1.6775771705000262),
 np.float64(0.20296101963598037),
 np.float64(2.195883054937527),
 np.float64(0.3565602369470712),
 np.float64(0.9127944350700514),
 np.float64(0.8207243447072301),
 np.float64(-0.038022141034273496),
 np.float64(0.9314612761179815),
 np.float64(0.3292549538762095),
 np.float64(0.20755937996993862),
 np.float64(2.7756725444888684),
 np.float64(1.5470601113462619),
 np.float64(1.3124059140973865),
 np.float64(0.43049074040891433),
 np.float64(0.10144252221240788),
 np.float64(0.3942808670934186),
 np.float64(-0.10371466858202125),
 np.float64(0.5541064281911506),
 np.float64(0.6834406587312991),
 np.float64(0.9651767464054849),
 np.float64(0.2753403594564774),
 np.float64(0.054645083780229094),
 np.float64(0.19165365726047812),
 np.float64(1.2895712848600895),
 np.float64(0.5202331334998826),
 np.float64(2.3238252972650075),
 np.float64(1.4621566952538358),
 np.float64(0.9288300844267781),
 np.float64(1.2822417371872592),
 np.float64(1.1679214142826233),
 np.float64(0.06451637239750474),
 np.float64(1.2677104777231618),
 np.float64(0.5602730161673082),
 np.float64(1.4558882048750232),
 np.float64(0.9226240018215778),
 np.float64(0.7769206219401317),
 np.float64(0.27620687486237466),
 np.float64(0.9165636268546093),
 np.float64(0.43294213142069055),
 np.float64(0.45386030122078463),
 np.float64(1.0224444162552453),
 np.float64(1.9801917920880698),
 np.float64(0.057254749433162846),
 np.float64(0.9566359586657975),
 np.float64(0.11943340656712469),
 np.float64(0.40913258408328274),
 np.float64(0.17612793763007872),
 np.float64(3.259006677931554),
 np.float64(1.1347595133673265),
 np.float64(0.5051032920245756),
 np.float64(0.6996711280319022),
 np.float64(0.4556279262448914),
 np.float64(0.7707652413114728),
 np.float64(1.1010445588036175),
 np.float64(0.5138557160913793),
 np.float64(0.09576467219245546),
 np.float64(3.3367208588538864),
 np.float64(3.000500343092974),
 np.float64(1.3272347897170205),
 np.float64(0.703790922487936),
 np.float64(0.2904743813057231),
 np.float64(3.5714172332386998),
 np.float64(0.46196307667145686),
 np.float64(1.0446976206261012),
 np.float64(0.5684759155118969),
 np.float64(0.20475646782066403),
 np.float64(1.4177545084023202),
 np.float64(2.3295600540566124),
 np.float64(0.7033924204826276),
 np.float64(0.20823546817450123),
 np.float64(0.08274937772018863),
 np.float64(2.49177688685107),
 np.float64(0.8211855148992571),
 np.float64(0.17839727518825851),
 np.float64(-0.5006420218419696),
 np.float64(0.10576536920411027),
 np.float64(1.5475289154191914),
 np.float64(0.15610555546494329),
 np.float64(0.8031263431638722),
 np.float64(1.5026952998661594),
 np.float64(0.7804772046379673),
 np.float64(0.1264929822824874),
 np.float64(2.303603950292662),
 np.float64(0.9418877056024676),
 np.float64(1.4973083402443332),
 np.float64(3.238661739194548),
 np.float64(1.7007531836121854),
 np.float64(3.957244815782449),
 np.float64(0.06239205873877074),
 np.float64(1.0760946665804487),
 np.float64(0.9855024218942453),
 np.float64(0.02370119702845237),
 np.float64(0.14958416988277778),
 np.float64(3.698062466328709),
 np.float64(0.7365894459993458),
 np.float64(1.1988183099934018),
 np.float64(0.2392689577598764),
 np.float64(0.4715054327981492),
 np.float64(2.4933204531658326),
 np.float64(1.6997632240896823),
 np.float64(0.9975956596736067),
 np.float64(0.6121953249773445),
 np.float64(0.0),
 np.float64(0.55274012283461),
 np.float64(0.25082250895724634),
 np.float64(0.4597947464379554),
 np.float64(0.4651287599100272),
 np.float64(-0.010535311248802748),
 np.float64(0.1307838931836227),
 np.float64(1.5111879771461407),
 np.float64(0.3254567758126895),
 np.float64(2.148839662625528),
 np.float64(0.02628695272542702),
 np.float64(1.6539590908906587),
 np.float64(1.5873953509492689),
 np.float64(1.2900519267998793),
 np.float64(0.00578648120301473),
 np.float64(1.2535787186240859),
 np.float64(1.1202251544855482),
 np.float64(1.116851541294217),
 np.float64(0.5480551323841226),
 np.float64(0.02746471220516313),
 np.float64(2.057975022455838),
 np.float64(0.6022835022755277),
 np.float64(1.0737405150105304),
 np.float64(3.2143647138939486),
 np.float64(0.42086705094184734),
 np.float64(1.0494596478070095),
 np.float64(0.4544743444319526),
 np.float64(0.20187339069317653),
 np.float64(2.3336141013372393),
 np.float64(0.6062618541065502),
 np.float64(1.0808978096528568),
 np.float64(0.009853599928993716),
 np.float64(-0.040347797500832075),
 np.float64(1.1278026229783042),
 np.float64(0.7289271396901905),
 np.float64(0.18854924659233033),
 np.float64(1.4204862482921408),
 np.float64(1.123447050874198),
 np.float64(0.48147002780771486),
 np.float64(1.0395843433056449),
 np.float64(1.2692452926936115),
 np.float64(2.127951401717149),
 np.float64(0.49046654250075883),
 np.float64(0.4252838905773258),
 np.float64(0.5877587563019999),
 np.float64(0.03686055281296211),
 np.float64(0.3912321781651906),
 np.float64(1.4222301446004393),
 np.float64(-0.0568627075491388),
 np.float64(0.5201551840779572),
 np.float64(0.2361906766564989),
 np.float64(2.994314323707567),
 np.float64(2.800982732894202),
 np.float64(0.3160866906337631),
 np.float64(0.38214425821512943),
 np.float64(1.9748917097648546),
 np.float64(1.2690722794832503),
 np.float64(1.1149429580453118),
 np.float64(0.13651259439426533),
 np.float64(1.9499242765902864),
 np.float64(1.4791283758278897),
 np.float64(0.7335732254553178),
 np.float64(4.028280582394392),
 np.float64(0.036486269185422054),
 np.float64(0.3430713545816495),
 np.float64(1.010291021675475),
 np.float64(0.014125276332641198),
 np.float64(-0.155476709738833),
 np.float64(1.8673573742235932),
 np.float64(0.9930712139328721),
 np.float64(1.1632000963155695),
 np.float64(0.3391910302783119),
 np.float64(0.0670197439909298),
 np.float64(1.6398173153795685),
 np.float64(0.33537362027281037),
 np.float64(0.8958508619061386),
 np.float64(2.013855621471108),
 np.float64(0.820959552388456),
 np.float64(0.06555328492038548),
 np.float64(1.3012842408714669),
 np.float64(0.48420595411626627),
 np.float64(2.6364267516321997),
 np.float64(3.6141823581619974),
 np.float64(0.21098873840620938),
 np.float64(1.003352124958146),
 np.float64(0.8325148854005832),
 np.float64(2.425911974857349),
 np.float64(-0.163235296172773),
 np.float64(1.0166600342739955),
 np.float64(0.025950310670482188),
 np.float64(0.043655579692313096),
 np.float64(1.095923286588916),
 np.float64(3.1890850967452034),
 np.float64(0.4320995560131773),
 np.float64(2.494883239714085),
 np.float64(3.0583122974511823),
 np.float64(0.17750525226853778),
 np.float64(2.437979991835749),
 np.float64(0.981355779071806),
 np.float64(0.9452984238886621),
 np.float64(0.8088963480581055),
 np.float64(2.7709069726776416),
 np.float64(2.047539166189979),
 np.float64(0.7950747892464551),
 np.float64(0.41320548803320817),
 np.float64(0.9185347245626894),
 np.float64(0.04150153943256251),
 np.float64(0.5962846592438421),
 np.float64(0.031433993986786646),
 np.float64(1.2660703415842185),
 np.float64(-0.07301108340810233),
 np.float64(2.114438073036242),
 np.float64(0.2825157767811463),
 np.float64(1.0376548597582862),
 np.float64(-0.03493710908984432),
 np.float64(2.6094081711968986),
 np.float64(0.5935594676713588),
 np.float64(0.3334554990301501),
 np.float64(0.05881473007502544),
 np.float64(2.1225220110444183),
 np.float64(0.6518088123711401),
 np.float64(0.24352879211373873),
 np.float64(0.04374844693926343),
 np.float64(0.08593572520842796),
 np.float64(0.04923575645103907),
 np.float64(0.7902450571481728),
 np.float64(0.8428144143501065),
 np.float64(0.07856508406047921),
 np.float64(0.600613115394615),
 np.float64(1.9129347287431586),
 np.float64(0.7482718942997444),
 np.float64(1.3764080064431927),
 np.float64(0.04242599892924201),
 np.float64(3.9642740474974287),
 np.float64(0.36869655597998346),
 np.float64(1.9748917097648546),
 np.float64(1.6863150812103225),
 np.float64(0.29740142525214797),
 np.float64(1.1314467578971268),
 np.float64(3.147224080405453),
 np.float64(1.6492379815374507),
 np.float64(1.2329711040514366),
 np.float64(0.48398904534850645),
 np.float64(0.2308825046156473),
 np.float64(2.618985531858209),
 np.float64(1.2313332296978668e-06),
 np.float64(0.7428827188334617),
 np.float64(0.5489593485737435),
 np.float64(0.5436087325248236),
 np.float64(1.5334476135302673),
 np.float64(0.12091007922558307),
 np.float64(1.5173627551803195),
 np.float64(1.5665636094064888),
 np.float64(0.8888672371063766),
 np.float64(2.8858562086565867),
 np.float64(0.15184597098527405),
 np.float64(0.5144660397120059),
 np.float64(1.77900563583054),
 np.float64(2.787959976535447),
 np.float64(0.07517609778865697),
 np.float64(1.0101481727285035),
 np.float64(0.9305766184186958),
 np.float64(1.18379301773128),
 np.float64(1.12110483276443),
 np.float64(0.1761870332625915),
 np.float64(1.162825814680664),
 np.float64(0.26942777923039546),
 np.float64(0.029722585550119748),
 np.float64(4.509231735926325),
 np.float64(1.3230223534366876),
 np.float64(2.2798826963982415),
 np.float64(-0.15201471727308388),
 np.float64(0.24581363039919274),
 np.float64(0.6885226622978146),
 np.float64(0.9554232352794138),
 np.float64(1.5613116275103185),
 np.float64(0.018282950586877983),
 np.float64(0.6775303829856388),
 np.float64(0.5959060478525011),
 np.float64(1.9975384485541234),
 np.float64(0.03770684153731387),
 np.float64(1.8606531911828392),
 np.float64(0.8270733707437818),
 np.float64(0.14255739150504462),
 np.float64(0.7058319692875038),
 np.float64(0.695366528614686),
 np.float64(2.04047746638396),
 np.float64(0.007081947643763797),
 np.float64(0.18533445842173413),
 np.float64(0.6667089484612327),
 np.float64(2.5819756393717226),
 np.float64(1.9894160833300896),
 np.float64(1.4001402120964779),
 np.float64(0.13274183550489677),
 np.float64(1.3370206349427214),
 np.float64(3.2212372194276364),
 np.float64(2.5608369066845595),
 np.float64(0.5077410042593701),
 np.float64(0.6494913432679388),
 np.float64(0.1605983059196027),
 np.float64(3.5006983523868525),
 np.float64(2.466268099572325),
 np.float64(1.6134747980600008),
 np.float64(0.21320563894319958),
 np.float64(2.1546968644027618),
 np.float64(0.752780149470355),
 np.float64(0.5474560593460702),
 np.float64(0.5071386195865357),
 np.float64(1.7655037621485694),
 np.float64(0.33749512633405726),
 np.float64(-0.48939413013409055),
 np.float64(2.0639509388995116),
 np.float64(0.009810441149647558),
 np.float64(0.3556937324547463),
 np.float64(0.16258446785838246),
 np.float64(0.1356560579268259),
 np.float64(0.020503815891312498),
 np.float64(1.273767282181152),
 np.float64(1.0631124582194043),
 np.float64(1.4217960810660595),
 np.float64(0.7734296058488793),
 np.float64(1.8704135261573605),
 np.float64(0.704136945356766),
 np.float64(0.058064473734789034),
 np.float64(0.27269020318947135),
 np.float64(1.7842247670182256),
 np.float64(0.03556472179774691),
 np.float64(2.390501820365414),
 np.float64(0.29367366054426947),
 np.float64(1.0666584530702066),
 np.float64(0.010474636850037298),
 np.float64(2.2749533088900376),
 np.float64(-0.02602781029420679),
 np.float64(0.286675726038131),
 np.float64(0.8355706411931687),
 np.float64(-0.09509098274647867),
 np.float64(0.774087658239387),
 np.float64(1.3173740537799),
 np.float64(0.22241705922267807),
 np.float64(0.25865078384254764),
 np.float64(0.953572470133649),
 np.float64(1.6970930145858554),
 np.float64(1.5621454059932538),
 np.float64(0.8006179905298692),
 np.float64(1.6569660601676195),
 np.float64(2.020339007609793),
 np.float64(1.9997378976430757),
 np.float64(0.3271865504503632),
 np.float64(0.6244440616303982),
 np.float64(0.8984682044100307),
 np.float64(-0.011408383144676185),
 np.float64(0.7844444290335181),
 np.float64(1.1857958972265643),
 np.float64(1.26048856996563),
 np.float64(2.3293523999143297),
 np.float64(1.4991211858213398),
 np.float64(0.5716215620131714),
 np.float64(1.1687084794722777),
 np.float64(1.1098826160186428),
 np.float64(0.3217214576753103),
 np.float64(0.13131959372344787),
 np.float64(1.5735234175858357),
 np.float64(2.014698203762629),
 np.float64(0.3506241131987454),
 np.float64(0.1677479508297459),
 np.float64(1.1130868682018296),
 np.float64(0.6617041295699432),
 np.float64(1.677725012261516),
 np.float64(0.7285808199445676),
 np.float64(3.1140516922609396),
 np.float64(0.44047090363700864),
 np.float64(2.069307476090657),
 np.float64(2.1577208034174573),
 np.float64(1.7222641991406236),
 np.float64(1.091154870848054),
 np.float64(0.6599751336564059),
 np.float64(0.3610430507940315),
 np.float64(0.7856239147401145),
 np.float64(1.8759033014127966),
 np.float64(0.34620929628557356),
 np.float64(0.3863630363328073),
 np.float64(0.639125995903561),
 np.float64(0.7371474851054077),
 np.float64(1.8739711911278505),
 np.float64(0.07264524929592246),
 np.float64(1.037677710947579),
 np.float64(2.822956060006352),
 np.float64(1.9372987989258135),
 np.float64(2.702177070216815),
 np.float64(0.44599813743585404),
 np.float64(1.7695352420108637),
 np.float64(0.4870523312646008),
 np.float64(3.521313640859681),
 np.float64(1.2983363328722177),
 np.float64(0.21226120155582293),
 np.float64(-0.04050972826376249),
 np.float64(1.3035916190398145),
 np.float64(0.34775464771386644),
 np.float64(1.4901161444860092),
 np.float64(1.4122458361062056),
 np.float64(0.6317786060593704),
 np.float64(1.2450754804245756),
 np.float64(2.324476946359801),
 np.float64(0.15910726581300352),
 np.float64(-0.05147623951186757),
 np.float64(0.5899074382446201),
 np.float64(1.471419250037055),
 np.float64(0.1590176049330619),
 np.float64(0.9732932821951701),
 np.float64(1.7882392328564005),
 np.float64(0.18358325337352416),
 np.float64(0.6710603985725679),
 np.float64(1.3787302815490121),
 np.float64(1.8516329799597109),
 np.float64(1.4814313171047246),
 np.float64(0.13606922887853223),
 np.float64(0.9757471777571387),
 np.float64(1.7883915623380697),
 np.float64(0.3054882895419429),
 np.float64(0.823694125949282),
 np.float64(0.5714486423787494),
 np.float64(1.732315085346997),
 np.float64(2.426981475956062),
 np.float64(0.06849182051024034),
 np.float64(2.568706445046229),
 np.float64(0.7797034786035304),
 np.float64(0.13174593750713812),
 np.float64(1.9743787543326121),
 np.float64(1.3304161224799416),
 np.float64(1.3233186499177387),
 np.float64(3.3426186042931874),
 np.float64(0.26604013307680435),
 np.float64(0.8735897953698438),
 np.float64(0.06014893210074703),
 np.float64(0.6008820094927758),
 np.float64(1.88574410982555),
 np.float64(-0.061569021501326426),

In [129]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)

In [131]:
print("Mse:",mse,"Rmse:",rmse)

Mse: 8.30217829172297 Rmse: 2.8813500814241526

In [ ]:
y

In [98]:
csr_matrix[test_rows,test_cols]

matrix([[4. , 1. , 3. , ..., 1. , 4. , 4.5]], shape=(1, 54179))

In [95]:
user_latent @ movie_latent

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 176274 is different from 50)

In [94]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix=cosine_similarity(user_latent,movie_latent)

MemoryError: Unable to allocate 356. GiB for an array with shape (270897, 176274) and data type float64